### ISSUE TITLE
won't install on mac/vscode

### ISSUE THREAD

**Issue by chovyprognos** [grimmer0125/vscode-back-forward-button#6] opened 2021-03-25 22:23 UTC
It doesn't show up in extensions search and the "install" button on the vscode page doesn't do anything.

**Comment by grimmerk** [comment] 2021-03-29 04:47
Could you supply more detail about your environment (e.g. Mac & VSCode version)? I use Mac and can not reproduce this issue.

Expect: 
After click install button,  the extension will be installed and later you can see the back-forward button on the states bar.

**Comment by grimmerk** [comment] 2021-10-12 16:52
I'm closing it since no detail. Please reopen it if it happens in the recent version.

**Closed as completed by grimmerk** 2021-10-12 16:52 UTC
